"""Model-Agnostic Wide Reranker with 1-Token Logprob Scoring & AST Chunking."""

from .adapters import (
    GenericOpenAIProfile,
    GemmaProfile,
    LFMProfile,
    ModelProfile,
    ProviderAdapter,
    QwenProfile,
    RWKVProfile,
    detect_profile_from_model_names,
    get_profile,
    probe_and_detect_profile_async,
    probe_and_detect_profile_sync,
    probe_tokenizer_tokens_sync,
)
from .cache import RerankCache
from .chunker import chunk_file, prepare_candidates
from .calibration import (
    BaseCalibrator,
    PlattScalingCalibrator,
    TemperatureScalingCalibrator,
    compute_brier_skill_score,
    compute_oof_predictions,
    compute_sharpness_distribution,
    compute_task_heldout_predictions,
    get_default_calibrator,
)
from .client import (
    LFMReranker,
    Reranker,
    apply_diversity_context_assembly,
    compute_symbol_match_delta,
    extract_binary_logprobs,
    extract_calibrated_logprobs,
    extract_code_identifiers,
    logsumexp,
)
from .config import (
    get_default_config_path,
    load_config,
    resolve_endpoint_and_model,
    save_config,
)
from .eval import (
    BootstrapCI,
    EvalReport,
    EvalTask,
    EvalTaskResult,
    calculate_bootstrap_confidence_intervals,
    calculate_brier_score,
    calculate_ece,
    generate_reliability_table,
    run_evaluation,
)
from .models import (
    AmbiguityEvent,
    CandidateChunk,
    CandidateManifestEntry,
    Citation,
    GroundTruthStatus,
    QueryIntent,
    RerankResponse,
    RerankResultItem,
    Telemetry,
)
from .verifier import GroundTruthVerifier

__version__ = "0.4.0"

__all__ = [
    "LFMReranker",
    "Reranker",
    "ModelProfile",
    "ProviderAdapter",
    "LFMProfile",
    "QwenProfile",
    "GemmaProfile",
    "RWKVProfile",
    "GenericOpenAIProfile",
    "get_profile",
    "detect_profile_from_model_names",
    "probe_and_detect_profile_sync",
    "probe_and_detect_profile_async",
    "probe_tokenizer_tokens_sync",
    "get_default_config_path",
    "load_config",
    "save_config",
    "resolve_endpoint_and_model",
    "RerankCache",
    "GroundTruthVerifier",
    "GroundTruthStatus",
    "QueryIntent",
    "Citation",
    "CandidateChunk",
    "CandidateManifestEntry",
    "RerankResultItem",
    "RerankResponse",
    "Telemetry",
    "AmbiguityEvent",
    "EvalReport",
    "EvalTask",
    "EvalTaskResult",
    "BootstrapCI",
    "calculate_bootstrap_confidence_intervals",
    "calculate_brier_score",
    "calculate_ece",
    "generate_reliability_table",
    "run_evaluation",
    "chunk_file",
    "prepare_candidates",
    "extract_calibrated_logprobs",
    "extract_binary_logprobs",
    "logsumexp",
    "BaseCalibrator",
    "PlattScalingCalibrator",
    "TemperatureScalingCalibrator",
    "compute_brier_skill_score",
    "compute_oof_predictions",
    "compute_sharpness_distribution",
    "compute_task_heldout_predictions",
    "get_default_calibrator",
    "compute_symbol_match_delta",
    "apply_diversity_context_assembly",
    "extract_code_identifiers",
]
